#!/bin/sh
# Pre-commit hook: run tests before allowing commit.
# Installed by: make install-hooks
# Runs from repo root so "make test" works regardless of current directory.
set -e
cd "$(git rev-parse --show-toplevel)" && make test
