#!/bin/sh
# Pre-commit hook: run "make test" before each commit.
# Install: run ./scripts/setup-hooks.sh from repo root (or symlink this file to .git/hooks/pre-commit)

set -e
cd "$(git rev-parse --show-toplevel)" || exit 1
exec 1>&2
echo "Running: make test"
make test
